<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FisrtFolderInTree</name>
   <tag></tag>
   <elementGuidId>2ca01363-c9b7-411b-bc9f-4cd03391c1f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;folder-preview&quot;]/ng-scrollbar/div/div/div/div[3]/app-node-item/div/div[1]/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;folder-preview&quot;]/ng-scrollbar/div/div/div/div[3]/app-node-item/div/div[1]/span[2]/span</value>
   </webElementProperties>
</WebElementEntity>
