<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuickFolder_btn</name>
   <tag></tag>
   <elementGuidId>70b3b40d-ec32-4917-870d-6b601b90bb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;expandViewWrapper&quot;]/div/div[2]/div[1]/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;expandViewWrapper&quot;]/div/div[2]/div[1]/div[2]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
