<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_btn</name>
   <tag></tag>
   <elementGuidId>1d66c682-781b-4755-80de-81fe74904935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-login-to-platform/div[1]/div/div/div[3]/div/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-login-to-platform/div[1]/div/div/div[3]/div/form/button</value>
   </webElementProperties>
</WebElementEntity>
